import { EditorThemeClasses } from "lexical";
import "./theme.css";

export const theme: EditorThemeClasses = {
    ltr: "ltr",
    rtl: "rtl",
    paragraph: "editor-paragraph",
    quote: "editor-quote",
    heading: {
        h1: "editor-heading-h1",
        h2: "editor-heading-h2",
        h3: "editor-heading-h3",
        h4: "editor-heading-h4",
        h5: "editor-heading-h5",
        h6: "editor-heading-h6",
    },
    list: {
        nested: {
            listitem: "editor-nested-list-item",
        },
        ol: "editor-list-ol",
        ul: "editor-list-ul",
        listitem: "editor-list-item",
        listitemChecked: "editor-list-item-checked",
        listitemUnchecked: "editor-list-item-unchecked",
    },
    hashtag: "editor-hashtag",
    image: "editor-image",
    link: "editor-link",
    text: {
        bold: "editor-textBold",
        capitalize: "editor-textCapitalize",
        code: "editor-textCode",
        highlight: "editor-textHighlight",
        italic: "editor-textItalic",
        lowercase: "editor-textLowercase",
        strikethrough: "editor-textStrikethrough",
        subscript: "editor-textSubscript",
        superscript: "editor-textSuperscript",
        underline: "editor-textUnderline",
        underlineStrikethrough: "editor-textUnderlineStrikethrough",
        uppercase: "editor-textUppercase",
    },
    code: "editor-code",
    codeHighlight: {
        "atrule": "editor-tokenAttr",
        "attr": "editor-tokenAttr",
        "boolean": "editor-tokenProperty",
        "builtin": "editor-tokenSelector",
        "cdata": "editor-tokenComment",
        "char": "editor-tokenSelector",
        "class": "editor-tokenFunction",
        "class-name": "editor-tokenFunction",
        "comment": "editor-tokenComment",
        "constant": "editor-tokenProperty",
        "deleted": "editor-tokenProperty",
        "doctype": "editor-tokenComment",
        "entity": "editor-tokenOperator",
        "function": "editor-tokenFunction",
        "important": "editor-tokenVariable",
        "inserted": "editor-tokenSelector",
        "keyword": "editor-tokenAttr",
        "namespace": "editor-tokenVariable",
        "number": "editor-tokenProperty",
        "operator": "editor-tokenOperator",
        "prolog": "editor-tokenComment",
        "property": "editor-tokenProperty",
        "punctuation": "editor-tokenPunctuation",
        "regex": "editor-tokenVariable",
        "selector": "editor-tokenSelector",
        "string": "editor-tokenSelector",
        "symbol": "editor-tokenProperty",
        "tag": "editor-tokenProperty",
        "url": "editor-tokenOperator",
        "variable": "editor-tokenVariable",
    },
    hr: "editor-hr",
};
