name: cd

on:
    workflow_run:
        workflows: ["ci"]
        types: [completed]

jobs:
    start-project:
        runs-on: server_tabbicus_fe

        steps:
            - name: đăng nhập docker hub
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u longbaolevu --password-stdin

            # - name: chạy lần đầu
            #   run: sudo docker compose up -d

            - name: Pull FE image mới nhất
              run: sudo docker compose -f docker-compose.yml pull FE

            - name: Recreate FE only (không đụng BE/DB/REDIS)
              run: sudo docker compose docker-compose.yml up -d
