name: cd

on:
    workflow_run:
        workflows: ["ci"]
        types: [completed]

jobs:
    start-project:
        runs-on: server_tabbicus_fe

        steps:
            - name: đăng nhập docker hub
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u longbaolevu --password-stdin

            # - name: chạy lần đầu
            #   run: sudo docker compose up -d

            - name: Kéo image mới về
              run: sudo docker compose pull FE

            - name: Tạo lại container FE
              run: sudo docker compose up -d --no-deps --force-recreate FE

            - name: Xoá các image không chạy
              run: sudo docker image prune -a -f
